force-app/main/default/objects/Data_Field__c/Data_Field__c.object-meta.xml
<CustomObject>
    <label>Data Field</label>
    <nameField>
        <label>Data Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Field__c/fields/Field_Id__c.field-meta.xml
<CustomField>
    <fullName>Field_Id__c</fullName>
    <formula>IF(
    AND(
        NOT(ISBLANK(Durable_Id__c)),
        CONTAINS(Durable_Id__c, &quot;.&quot;),
        Custom__c = TRUE
    ),
    RIGHT(
        Durable_Id__c,
        LEN(Durable_Id__c) - FIND(&quot;.&quot;, Durable_Id__c)
    ),
    NULL
)</formula>
    <label>Field Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Metadata_Component_Reference__c/Metadata_Component_Reference__c.object-meta.xml
<CustomObject>
    <label>Metadata Component Reference</label>
    <nameField>
        <displayFormat>MCR-{000000}</displayFormat>
        <label>Metadata Component Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metadata Component References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Metadata_Component_Reference__c/fields/Component_Id__c.field-meta.xml
<CustomField>
    <fullName>Component_Id__c</fullName>
    <label>Component Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Metadata_Component_Reference__c/fields/Component_Namespace__c.field-meta.xml
<CustomField>
    <fullName>Component_Namespace__c</fullName>
    <label>Component Namespace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Metadata_Component_Reference__c/fields/Component_Type__c.field-meta.xml
<CustomField>
    <fullName>Component_Type__c</fullName>
    <label>Component Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ApexClass</fullName>
            </value>
            <value>
                <fullName>ApexComponent</fullName>
            </value>
            <value>
                <fullName>ApexTrigger</fullName>
            </value>
            <value>
                <fullName>CustomField</fullName>
            </value>
            <value>
                <fullName>EmailTemplate</fullName>
            </value>
            <value>
                <fullName>FieldSet</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Layout</fullName>
            </value>
            <value>
                <fullName>LookupFilter</fullName>
            </value>
            <value>
                <fullName>ValidationRule</fullName>
            </value>
            <value>
                <fullName>WorkflowFieldUpdate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Metadata_Component_Reference__c/fields/Data_Field__c.field-meta.xml
<CustomField>
    <fullName>Data_Field__c</fullName>
    <label>Data Field</label>
    <referenceTo>Data_Field__c</referenceTo>
    <relationshipLabel>Metadata Component References</relationshipLabel>
    <relationshipName>Metadata_Component_References</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DataDictionaryReference_Batch.cls
global class DataDictionaryReference_Batch implements Database.Batchable<sObject>, Database.RaisesPlatformEvents, Database.AllowsCallouts, Database.Stateful {
    public static final String QUERY_TEMPLATE =
        'SELECT MetadataComponentType, MetadataComponentName, RefMetadataComponentName, RefMetadataComponentId, RefMetadataComponentType, MetadataComponentId, MetadataComponentNamespace ' +
        'FROM MetadataComponentDependency ' +
        'WHERE RefMetadataComponentType = \'CustomField\' and RefMetadataComponentId = {0} ' +
        'ORDER By RefMetadataComponentName';
    private String originalTransactionId;

    global Iterable<sObject> start(Database.BatchableContext bc) {
        this.originalTransactionId = Logger.getTransactionId();

        List<Data_Field__c> dataFields = [
            SELECT Id, Name, Field_Id__c
            FROM Data_Field__c
            WHERE Field_Id__c != NULL
        ];

        Logger.info('Starting DataDictionaryReference_Batch');
        Logger.saveLog();

        return dataFields;
    }

    global void execute(
        Database.BatchableContext bc,
        List<Data_Field__c> scope
    ) {
        Logger.setParentLogTransactionId(this.originalTransactionId);

        List<Metadata_Component_Reference__c> existingReferences = [
            SELECT
                Id,
                Name,
                Component_Id__c,
                Component_Type__c,
                Component_Namespace__c,
                Component_Name__c,
                External_Id__c,
                Data_Field__c,
                Data_Field__r.Field_Id__c
            FROM Metadata_Component_Reference__c
        ];
        Map<String, Metadata_Component_Reference__c> existingReferencesMap = new Map<String, Metadata_Component_Reference__c>();
        for (Metadata_Component_Reference__c mc : existingReferences) {
            existingReferencesMap.put(mc.External_Id__c, mc);
        }

        Map<String, Metadata_Component_Reference__c> referencesToUpsert = new Map<String, Metadata_Component_Reference__c>();
        Map<String, Metadata_Component_Reference__c> referencesToDelete = new Map<String, Metadata_Component_Reference__c>();

        for (Data_Field__c dataField : scope) {
            Map<String, Object> untype = DataDictionaryHttpClass.getMetadataReferences(
                String.format(
                    QUERY_TEMPLATE,
                    new List<String>{ '\'' + dataField.Field_Id__c + '\'' }
                ),
                UserInfo.getSessionId()
            );

            try {
                List<Object> references = (List<Object>) untype.get('records');

                for (Object ref : references) {
                    Map<String, Object> reference = (Map<String, Object>) ref;
                    String key =
                        dataField.Field_Id__c +
                        '|' +
                        (String) reference.get('MetadataComponentId');
                    Metadata_Component_Reference__c newReference = new Metadata_Component_Reference__c(
                        Data_Field__c = dataField.Id,
                        Component_Id__c = (String) reference.get(
                            'MetadataComponentId'
                        ),
                        Component_Type__c = (String) reference.get(
                            'MetadataComponentType'
                        ),
                        Component_Namespace__c = (String) reference.get(
                            'MetadataComponentNamespace'
                        ),
                        Component_Name__c = (String) reference.get(
                            'MetadataComponentName'
                        ),
                        External_Id__c = key
                    );

                    referencesToUpsert.put(key, newReference);
                }
            } catch (Exception e) {
                Logger.error('Exception Error Message.', e);
                system.debug('Exception Error Message: ' + e.getMessage());
                continue;
            }
        }

        if (!referencesToUpsert.isEmpty()) {
            List<Database.UpsertResult> result = Database.upsert(
                referencesToUpsert.values(),
                Metadata_Component_Reference__c.Fields.External_Id__c,
                false
            );
            Logger.info('Upserting Metadata Component References', result);
        }

        for (Metadata_Component_Reference__c reference : existingReferences) {
            if (!referencesToUpsert.containsKey(reference.External_Id__c)) {
                referencesToDelete.put(reference.External_Id__c, reference);
            }
        }

        if (!referencesToDelete.isEmpty()) {
            List<Database.DeleteResult> result = Database.delete(
                referencesToDelete.values(),
                false
            );
            Logger.info('Deleting Metadata Component References', result);
        }

        Logger.saveLog();
    }
    global void finish(Database.BatchableContext bc) {
        Logger.setParentLogTransactionId(this.originalTransactionId);

        Logger.info('Finishing running DataDictionaryReference_Batch');
        Logger.saveLog();
    }
}